name: draw_hub
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_lint: ^3.0.3
  # Routing
  go_router: ^16.3.0


  # UI
  cupertino_icons: ^1.0.8


  # Firebase
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5

  # image from gallery
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  image: ^4.7.2
  # Path provider for file system access
  path_provider: ^2.1.5

  # Validation
  email_validator: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter



  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf